### ISSUE TITLE
lvcreate

### ISSUE THREAD

**Issue by cnckh** [lvmteam/lvm2#100]
![image](https://user-images.githubusercontent.com/76078640/207013666-b898f6a4-5634-409c-ad2b-650d6c6edcb8.png)
![image](https://user-images.githubusercontent.com/76078640/207014022-f647be0b-bef5-45b7-b03e-cf6b8935baba.png)
create lv fail!
May I ask how to solve or avoid it?
 lvm version
  LVM version:     2.03.14(2) (2021-10-20)
  Library version: 1.02.181 (2021-10-20)
  Driver version:  4.43.0
  Configuration:   ./configure --build=x86_64-openEuler-linux-gnu --host=x86_64-openEuler-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-default-dm-run-dir=/run --with-default-run-dir=/run/lvm --with-default-pid-dir=/run --with-default-locking-dir=/run/lock/lvm --with-usrlibdir=/usr/lib64 --enable-fsadm --enable-write_install --with-user= --with-group= --with-device-uid=0 --with-device-gid=6 --with-device-mode=0660 --enable-pkgconfig --enable-applib --enable-cmdlib --enable-dmeventd --enable-blkid_wiping --with-cluster=internal --with-clvmd=none --with-udevdir=/usr/lib/udev/rules.d --enable-udev_sync --with-thin=internal --with-thin=internal --enable-lvmpolld --enable-lvmlockd-sanlock --enable-dbus-service --enable-notify-dbus --enable-dmfilemapd

**Comment by cnckh** [comment]
> ![image](https://user-images.githubusercontent.com/76078640/207013666-b898f6a4-5634-409c-ad2b-650d6c6edcb8.png) ![image](https://user-images.githubusercontent.com/76078640/207014022-f647be0b-bef5-45b7-b03e-cf6b8935baba.png) create lv fail! May I ask how to solve or avoid it?
 lvm version
  LVM version:     2.03.14(2) (2021-10-20)
  Library version: 1.02.181 (2021-10-20)
  Driver version:  4.43.0
  Configuration:   ./configure --build=x86_64-openEuler-linux-gnu --host=x86_64-openEuler-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-default-dm-run-dir=/run --with-default-run-dir=/run/lvm --with-default-pid-dir=/run --with-default-locking-dir=/run/lock/lvm --with-usrlibdir=/usr/lib64 --enable-fsadm --enable-write_install --with-user= --with-group= --with-device-uid=0 --with-device-gid=6 --with-device-mode=0660 --enable-pkgconfig --enable-applib --enable-cmdlib --enable-dmeventd --enable-blkid_wiping --with-cluster=internal --with-clvmd=none --with-udevdir=/usr/lib/udev/rules.d --enable-udev_sync --with-thin=internal --with-thin=internal --enable-lvmpolld --enable-lvmlockd-sanlock --enable-dbus-service --enable-notify-dbus --enable-dmfilemapd

**Comment by zkabelac** [comment]
Hello

Can you please provide  'lvcreate -vvvv'  trace ?

Ideally attach   'lvmdump' output as well.

**Comment by cnckh** [comment]
This problem is occasional and will provide you with detailed information after recurrence. 
Thank you.

**Comment by cnckh** [comment]
![image](https://user-images.githubusercontent.com/76078640/218944967-072291f6-8b4f-47d6-bb04-9321cb5a4ca9.png)
lvcreate -vvvv
Execution result



 Internal error: LV 8d30b9c6-aed3-4267-86af-404fc5bd5757/fe5e0a8c-8a4f-42f9-9132-c87ad4d3a2e3__74a13687-d0a0-4e20-b43d-f8e9bf197235 has duplicate lock_args 1.0.0:80740352.
  Unlock: Memlock counters: prioritized:0 locked:0 critical:0 daemon:0 suspended:0
  Syncing device names
  Udev cookie 0xd4da20f (semid 17) decremented to 0
  Udev cookie 0xd4da20f (semid 17) waiting for zero
  Udev cookie 0xd4da20f (semid 17) destroyed
  8d30b9c6--aed3--4267--86af--404fc5bd5757-lvmlock: Skipping NODE_ADD (252,2) 0:6 0660 [trust_udev]
  8d30b9c6--aed3--4267--86af--404fc5bd5757-lvmlock: Processing NODE_READ_AHEAD 0 (flags=0)
  8d30b9c6--aed3--4267--86af--404fc5bd5757-lvmlock (252:2): Setting read ahead to 0
  Unlocking /run/lock/lvm/V_8d30b9c6-aed3-4267-86af-404fc5bd5757
  _undo_flock /run/lock/lvm/V_8d30b9c6-aed3-4267-86af-404fc5bd5757
  Freeing VG 8d30b9c6-aed3-4267-86af-404fc5bd5757 at 0x55ac515f20a0.
  Freeing VG 8d30b9c6-aed3-4267-86af-404fc5bd5757 at 0x55ac515b2530.
  lockd VG 8d30b9c6-aed3-4267-86af-404fc5bd5757 mode un
  lockd_result 0 flags none lm sanlock
  lvmlockd lock_vg un vg 8d30b9c6-aed3-4267-86af-404fc5bd5757 result 0 0
  Closing daemon socket (fd 3).
  global/notify_dbus not found in config: defaulting to 1
  Destroy lvmcache content
  Completed: lvcreate -asy -L 1077936128byte 8d30b9c6-aed3-4267-86af-404fc5bd5757 -n fe5e0a8c-8a4f-42f9-9132-c87ad4d3a2e3__74a13687-d0a0-4e20-b43d-f8e9bf197235 -y -vvv

**Comment by teigland** [comment]
Hi, please ensure that you are using "-vvvv" (four v's), and then we will need to see the complete debug output from that command.  You could also collect logs for all lvm commands by setting in lvm.conf log section level=7 file="/tmp/lvm.log" (or some other file location.)  This log file could grow large depending on how many commands are run, so you may need to watch it and delete it periodically.  You could then upload that log file somewhere for us to look at it.  After the command fails, could you also include the file /etc/lvm/backup/<vgname>

**Comment by cnckh** [comment]
There is a logical volume renewal disconnected.
Try to renew the contract
sanlock  client init -r lvm_vg_multipath3:FCdJVq-xYCb-7S8B-7hm8-rFXs-6q0f-0tX9NV:/dev/mapper/vg_multipath3-lvmlock:72351744:SH -p 2581
Solve!
