### ISSUE TITLE
Improve lvs output for raid + caching

### ISSUE THREAD

**Issue by mnlipp** [lvmteam/lvm2#107]
I have configured LV raid1 and then added SSD caching. Works great. The only irritating issue is the output from lvs:
```
  LV      VG     Attr       LSize  Pool                  Origin          Data%  Meta%  Move Log Cpy%Sync Convert
  al_root vgmain Cwi-aoC--- 80.00g [al_root_cache_cpool] [al_root_corig] 3.41   15.57           0.00            
```

My RAID1 *is* synced, as I can see with `lvs -a`:
```
  LV                          VG     Attr       LSize  Pool                  Origin          Data%  Meta%  Move Log Cpy%Sync Convert
  al_root                     vgmain Cwi-aoC--- 80.00g [al_root_cache_cpool] [al_root_corig] 3.41   15.57           0.00            
  [al_root_cache_cpool]       vgmain Cwi---C--- 16.00g                                       3.41   15.57           0.00            
  [al_root_cache_cpool_cdata] vgmain Cwi-ao---- 16.00g                                                                              
  [al_root_cache_cpool_cmeta] vgmain ewi-ao---- 20.00m                                                                              
  [al_root_corig]             vgmain rwi-aoC--- 80.00g                                                              100.00          
  [al_root_corig_rimage_0]    vgmain iwi-aor--- 80.00g                                                                              
  [al_root_corig_rimage_1]    vgmain iwi-aor--- 80.00g                                                                              
  [al_root_corig_rmeta_0]     vgmain ewi-aor---  4.00m                                                                              
  [al_root_corig_rmeta_1]     vgmain ewi-aor---  4.00m                                                                              
```

Of course, it's `al_root_corig` that's synced and gets the 100%.

What I expect lvs to output for `al_root` is either 100% (taken from ..._corig) or an empty field (because you could argue that `al_root` "as a whole" is not RAID and so the percentage doesn't apply). But the current output is "disturbing".

**Comment by zkabelac** [comment]
Displayed value is correct - as it applies to 'dirty' cache percentage  (aka 0.0% means - whole cache is in sync with origin - 100% would mean - cache is filled to max capacity with dirty blocks that need to be synced to origin -   if you would be using i.e. writeback mode)

We would possibly need some better way to display  'tree-level' entries

**Comment by mnlipp** [comment]
I had not been aware that the cache has a valid sync-value of it's own. But makes sense, of course. (I've never used write caching, so it simply didn't cross my mind.) Thanks!
