### ISSUE TITLE
Error with `lvresize`: `/usr/libexec/lvresize_fs_helper: execvp failed: No such file or directory`

### ISSUE THREAD

**Issue by franalbani** [lvmteam/lvm2#124]
I'm on Arch Linux, and since some recent update ([maybe](https://gitlab.archlinux.org/archlinux/packaging/packages/lvm2/-/commit/c9c512943bb37941a7fab1cff72a177b3eba7f3c) ) I'm unable to shrink a volume because `/usr/libexec/lvresize_fs_helper` is missing.

```console
$ lvresize -L -1G --resizefs /dev/volgroup/vol
  File system ext4 found on volgroup/vol.
  File system size (14.00 GiB) is larger than the requested size (13.00 GiB).
  File system reduce is required using resize2fs.
  File system fsck will be run before reduce.
  Reducing file system ext4 to 13.00 GiB (13958643712 bytes) on volgroup/vol...
  /usr/libexec/lvresize_fs_helper: execvp failed: No such file or directory
  Failed to reduce file system with lvresize_fs_helper.
```

Arch Linux does not use `/usr/libexec` so this may be a packaging problem, but I can't find `lvresize_fs_helper` anywhere

```console
$ find / -iname "*lvresize_fs_helper*" | wc -l
0
```

 Rolling back to the previous version (`2.03.21-1`) solved the problem.

I've also opened https://bugs.archlinux.org/task/79352 just in case.

**Comment by eworm-de** [comment]
A `make install_lvm2` does not include `make install_libexec`. I think it should, so opened #125.

Still unsure why this pops up with `2.03.22-1`, but was fine in `2.03.21-1`. Neither of both includes `lvresize_fs_helper`.

**Comment by FlorentFlament** [comment]
Hi, I have the same issue with lvm2 2.03.27-1 (Debian package).

**Comment by cweiske** [comment]
Debian problem was reported at https://bugs-devel.debian.org/cgi-bin/bugreport.cgi?bug=1065606 and should be fixed since 2025-03-03.
