### ISSUE TITLE
Using lv devices while initial syncing

### ISSUE THREAD

**Issue by lignumqt** [lvmteam/lvm2#142]
Hello everyone!
I'm not sure where I should ask, pls sorry if I'm wrong and put it here. It'd be helpful if you can send link where I may ask such questions.

I want to use lv raid6(and other raid) and it requires to do initial resync, but I'm not sure if I can use the device(or several devices at the same time) while initial resync, for instance sharing this lv to vmware and create some VM or smth like that. Is it safe to use the device during the initial resync? Will my data be damaged?

I couldn't find any information in docs. If there's some info there pls tell me where.

Thanks!

**Comment by zkabelac** [comment]
LV device is fully usable from the moment of creation.  Synchronization of raid array is a background task which may in cases of large arrays take even days.

User can influence the speed of resync (faster resync -> higher disk resource abuse).

For some cases its worth to consider to create raid array with  --nosync options - although it has some drawbacks as it is limiting some feautures....
