### ISSUE TITLE
Space on LVM partition is not freed up after deleting files

### ISSUE THREAD

**Issue by vukitoso** [lvmteam/lvm2#145]
Hello.
There is a partition /dev/mapper/ubuntu--vg-ubuntu--lv
The disk is 100% full.
I deleted 15 GB of files - logs from modSecurity for Apache2, but df -h shows that the disk is 100% full.

As a temporary solution, we added more space to the virtual machine, but the vacated space has not yet become available somewhere. It’s as if the information about the available space was cached.

How to "get" free space?
Thx.

**Comment by zkabelac** [comment]
Hello - your question is likely 'filesystem' related -  so  lvm2 has nothing to do with this case.

However typical things to look at could be -  your 'root' running software is using 'disk space' to it's full potentiall - while the 'non-root' user has to live with  5% (or whatever number picked by filesystem)  reserve  - so root can still write  using some 'reserved' space, while user cannot write anything anymore -  this space can be pretty large for large filesystems - so even removing 15G could be still not enough.

Other thing to check is - you have some daemon constantly filling your disk space - so unless you kill it - you can't win  - usually  'reboot' is great help here....

There can be tons of other reason where the lost space is in your filesystem - and there are lots of tools to detect i.e. largest files....

Anyway - closing as this is not an lvm2 issue...
