### ISSUE TITLE
Support discard(trim) with raidintegrity

### ISSUE THREAD

**Issue by cktkw** [lvmteam/lvm2#149]
Currently RAID alone supports DISCARD, but not when integrity is added.
Dm-Integrity now has `allow_discard` option, so it would be nice if DISCARD is enabled for raidintegrity.

I'm assuming this doesn't require much change, but I'm not familiar with LVM or Linux so this issue is more of a friendly reminder that dm-integrity now has DISCARD support.
It would be nice if it's supported, but I understand there are other more important things to work on.

Apologies if this isn't the right place to ask, and thank you in advance.

**Comment by teigland** [comment]
Here's a devel patch adding `--integritysettings` that can be used to set several kernel tunables for integrity, including allow_discards:
https://gitlab.com/lvmteam/lvm2/-/tree/dev-dct-integritysettings

There is some more work to do before the patch will be in its final form to push into an lvm release.

**Comment by teigland** [comment]
pushed to main branch
https://gitlab.com/lvmteam/lvm2/-/commit/78d14a805c3133c9a633a61c7751a81ebfae4d99
