### ISSUE TITLE
Man pages give incorrect instructions to view the list of available fields

### ISSUE THREAD

**Issue by josephcsible** [lvmteam/lvm2#165]
The man pages for `pvdisplay`, `vgdisplay`, `lvdisplay`, and `lvm-fullreport` all include the following text:

> Use **-o help** to view the list of all available fields.

But that doesn't actually work: `pvdisplay -o help`, `vgdisplay -o help`, and `lvdisplay -o help` all give an `Incompatible options selected` error, and `lvm fullreport -o help` just gives the same output as `lvm fullreport` with no arguments.

**Comment by zkabelac** [comment]
Hmm  -  it does look like there is some inconsistency from man page generation.

This '-o' is for commands  'pvs/vgs/lvs'

I'll check - thanks for noticing.

**Comment by prajnoha** [comment]
This is just the same text used for all man pages. The pv/vg/lvdisplay needs to use -C in addition (to switch into "report/column" mode). The lvm fullreport needs "--configreport" in addition for the "-o" to be usable.

**Comment by zkabelac** [comment]
Yep - the man page will need extra clarification -  as  the option  '-C'  will simply switch command   pvdisplay -> pvs,  lvdisplay -> lvs,  vgdisplay -> vgs.

So we should probably make there  2 'entries' for such commands i.e.  one showing  'old' pvdisplay and one  referring  to  'pvs'.
As ATM it might look a bit confusing a single command has 'many' acceptable option
usable only in certain cases.

**Comment by zkabelac** [comment]
Man pages were updated upstream with this patch:
https://github.com/lvmteam/lvm2/commit/e8e4324d68bb6ce711b09679e9c83d986bd4a5ee

Considering this as mostly fixed - we may eventually couple more sentences here and there over the time...

**Comment by josephcsible** [comment]
Is it intentional that the "SYNOPSIS" section now contains a second copy of all of the flags, without any kind of grouping?

**Comment by zkabelac** [comment]
Our the 'SYNOPSIS' section always shows  ALL supported options for the command for quick overlook.

Then follows the 'USAGE' section with individual variants and supported subsets of options - i.e. check 'lvconvert'  man page.

So far we see it as reasonable way how to easily 'hunt' for option if you are 'experienced' user or then look for more detailed 'command' description if you need to know more info.

So yes it's fully intentional.
