### ISSUE TITLE
Update manpage regarding integrity raid limitations and repairs

### ISSUE THREAD

**Issue by SyntheticBird45** [lvmteam/lvm2#166]
Some point after I briefly experimented with lvm raidintegrity (which imo should deserve more love and attention online)

From [lvmraid(7)](https://man.archlinux.org/man/lvmraid.7):
> The following are not yet permitted on RAID LVs with integrity:
       lvreduce, pvmove, lvconvert --splitmirrors, lvchange
       --syncaction, lvchange --rebuild.

While in fact, `lvchange --syncaction check` is supported and `repair` redirect to it too.
There are no informations in man about what algorithm is used with dm-integrity...
And lastly, I know this has been said prior in the text but could there be an **Integrity repairs** section stating that you need to first
disable integrity before adding another drive and delete the missing one.

**Comment by teigland** [comment]
Thanks, I pushed out some minor updates to the man page.
