### ISSUE TITLE
how to enable lvm for this version？？

### ISSUE THREAD

**Issue by kevinwd** [lvmteam/lvm2#28]
**how to enable lvm for this version？？** 
 LVM version:     2.03.10(2)-git (2020-03-26)
 Library version: 1.02.173-git (2020-03-26)
 Driver version:  4.35.0
 Configuration:   ./configure 

I can't find lvm2 service on my machine。
![image](https://user-images.githubusercontent.com/29305054/80465212-7d02d680-896d-11ea-97b7-0f85e295601a.png)

**Comment by kevinwd** [comment]
how to enable lvm for this version？？
LVM version: 2.03.10(2)-git (2020-03-26)
Library version: 1.02.173-git (2020-03-26)
Driver version: 4.35.0
Configuration: ./configure

I can't find lvm2 service on my machine。
![Screen Shot 2020-04-28 at 4 25 06 PM](https://user-images.githubusercontent.com/29305054/80465298-9441c400-896d-11ea-8caf-b6e92db3a1e7.png)

**Comment by kevinwd** [comment]
![Screen Shot 2020-04-28 at 4 25 06 PM](https://user-images.githubusercontent.com/29305054/80465373-a885c100-896d-11ea-8ead-53d19d5ff843.png)

**Comment by kevinwd** [comment]
root@VersaPLX01:/home/horatio# cd /etc/init.d/ 
root@VersaPLX01:/etc/init.d# ls
apparmor          cron        iscsid             nmbd        plymouth      rsync                smbd              udev
atop              dbus        keyboard-setup.sh  ntp         plymouth-log  rsyslog              socketserver1.sh  ufw
atopacct          drbd        kmod               open-iscsi  postfix       rtslib-fb-targetctl  ssh               uuidd
console-setup.sh  hwclock.sh  logd               openhpid    pppd-dns      samba-ad-dc          sysstat           x11-common
corosync          irqbalance  network-manager    pacemaker   procps        selinux-autorelabel  target

**Comment by zkabelac** [comment]
lvm2 services are related to systemd  so expecting them in  /etc/init.d/ is not the right way how to check for them -
see:  'systemctl -a'  command for more details.

When lvm2 is compiled without systemd support (which should be made if you do not use 'systemd' enabled distribution), it's not using 'services' it just forks this 'daemons' from executed command.

**Comment by zkabelac** [comment]
Assuming this was a users' system installation task.
