### ISSUE TITLE
LVM2.2.03.11/daemons/lvmlockd/lvmlockd-core.c: 2* off by one errors ?

### ISSUE THREAD

**Issue by dcb314** [lvmteam/lvm2#44]
1.

LVM2.2.03.11/daemons/lvmlockd/lvmlockd-core.c:900:8: error: Width 16 given in format string (no. 3) is larger than destination buffer 'lm_type_str[16]', use %15s to prevent overflowing it. [invalidScanfFormatWidth]

2.

LVM2.2.03.11/daemons/lvmlockd/lvmlockd-core.c:920:8: error: Width 8 given in format string (no. 4) is larger than destination buffer 'mode[8]', use %7s to prevent overflowing it. [invalidScanfFormatWidth]

**Comment by zkabelac** [comment]
Fixed with upstream commit -  a4c56a3bc342ab42fdfc9c9538b3fa7feba49412
