### ISSUE TITLE
With CentOS 8, configure the lvm2 failed before precompile,  and the  libcpg package is required? 

### ISSUE THREAD

**Issue by guozhonghua216** [lvmteam/lvm2#46]
checking pkg-config is at least version 0.9.0... yes
checking for PKGCONFIGINIT... no
pkg-config initialized
checking for CPG... no
configure: error: Package requirements (libcpg) were not met:

Package 'libcpg', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables CPG_CFLAGS
and CPG_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

How to deal with this issue, thanks!

**Comment by guozhonghua216** [comment]
While disable the --enable-cmirrord option, the error dispeared.

**Comment by zkabelac** [comment]
lvm2 with cmirrord  requires CPG library.
If the user does not need 'cmirrord'  he should not enable with --enable-cmirrord.
