### ISSUE TITLE
git clone problems

### ISSUE THREAD

**Issue by cruise2018** [lvmteam/lvm2#53]
When I tried to clone the code from this reporitory with windows 10 and gitbash(2.32.0) , i get a error like this:
Cloning into 'lvm2'...
warning: ----------------- SECURITY WARNING ----------------
warning: | TLS certificate verification has been disabled! |
warning: ---------------------------------------------------
warning: HTTPS connections may not be secure. See https://aka.ms/gcmcore-tlsverify for more information.
remote: Enumerating objects: 135637, done.
remote: Counting objects: 100% (4613/4613), done.
remote: Compressing objects: 100% (1661/1661), done.
remote: Total 135637 (delta 3292), reused 3861 (delta 2914), pack-reused 131024
Receiving objects: 100% (135637/135637), 37.34 MiB | 2.39 MiB/s, done.
Resolving deltas: 100% (104906/104906), done.
error: invalid path 'test/lib/aux.sh'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
 I finally find that the aux.sh file name cause this proble.  Then I create a issue on git, but they say it is filename proble(anyway, i don't think so). So if any probility to change the file name?

**Comment by cruise2018** [comment]
and i also find that.It's only about aux.sh file name, and has nothing to do with which directory it is in and what content in this file.
Please fix this problem.

**Comment by mms0536** [comment]
This problem is caused by the reserved words in Windows. The reserved words in the file name must be avoided. Currently, the following reserved words are known:
```
CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9
```
([Reserved Word Quoted From](https://www.howtogeek.com/fyi/windows-10-still-wont-let-you-use-these-file-names-reserved-in-1974/))

**Comment by zkabelac** [comment]
I'm just wondering in the first place what is the reason to checkout linux  lvm2  on Windows  machine ?
It's certainly not usable there at all as it is targeted to operate with 'DM' devices only.

And does that mean you would like to see only the testing filename   'aux.sh' to be renamed to something else ??

It's somewhat confusing...

**Comment by bmr-cymru** [comment]
On Windows you should use a POSIX compatible environment like [Windows Subsystem for Linux (WSL)](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux) or [Cygwin](https://www.cygwin.com/), or a virtualisation environment that allows you to run a Linux distribution to work with the LVM2 sources.

LVM2 is a Linux/POSIX compatible application and does not target Windows for either build or development, and Windows lacks the device-mapper subsystem that would be needed to use the resulting binaries anyway - this is not a bug in the LVM2 project, it is just not designed to be compatible with Windows file system, build, or runtime expectations.

**Comment by zkabelac** [comment]
Since there is no more reaction - closing as  it is really not worth changing some core script names for a platform that has no use for the project AFAIK
