### ISSUE TITLE
segmentation faults with uClibc-ng

### ISSUE THREAD

**Issue by wbx-github** [lvmteam/lvm2#6]
When using a system with uClibc-ng for embedded targets with Buildroot or
Gentoo/hardened on Desktop there is a segmentation fault trying to use cryptsetup.
The reason for it is, that uClibc-ng does not support symbol versioning.

See here a workaround:
https://bugs.busybox.net/attachment.cgi?id=7496&action=diff&collapsed=&headers=1&format=raw

Is the combat code still required in libdm/ioctl/libdm-iface.c?

Thanks

**Comment by mniestroj** [comment]
Hi.
Please see my patch here: https://www.redhat.com/archives/dm-devel/2018-July/msg00187.html
In general after applying this patch you can compile lvm2 with --disable-symvers option, so lvm2 under uclibc will work successfully.

**Comment by zkabelac** [comment]
Issue resolved with option  --with-symvers   / --without-symvers   based on this originating patch for upstream lvm2 2.03.12 in this commit: 1cedbaf13778de02e38b5dc80a7af246b7ec83e5.

https://listman.redhat.com/archives/lvm-devel/2021-March/msg00298.html
