### ISSUE TITLE
LVM2.2.02.179/lib/metadata/metadata.c: confused logic ?

### ISSUE THREAD

**Issue by dcb314** [lvmteam/lvm2#7]
LVM2.2.02.179/lib/metadata/metadata.c:4125] -> [LVM2.2.02.179/lib/metadata/metadata.c:4179]: (warning) Identical inner 'if' condition is always true.

Line 4125 is 

     if (!correct_vg) {

and line 4179 is 

                 if (!correct_vg) {
                                correct_vg = vg;
                                if (!_update_pv_list(cmd->mem, &all_pvs, correct_vg)) {
                                        _free_pv_list(&all_pvs);
                                        fid->ref_count--;
                                        release_vg(vg);
                                        return_NULL;
                                }
                                continue;
                        }

which means that the continue always executes and so the rest of the code
in the block can never execute. Looks suspicious to me.

**Comment by zkabelac** [comment]
I guess - the loop is processing the list of metadata - and the first metadata goes through here - is marked 'correct_vg'  - continue then means to go and get the 'next' metadata set.
Next iteration witll have 'correct_vg !=NULL'  so it will skip this  if().
