### ISSUE TITLE
lvm2 2.03.15 fails to compile due to multiple definitions of dm_bitset_parse_list

### ISSUE THREAD

**Issue by Zopolis4** [lvmteam/lvm2#71]
On armv7l ChromeOS, trying to compile lvm2 with deventd enabled, but the build fails on the following error:
```
/usr/local/bin/ld.gold: warning: using 'DM_1_02_129' as version for 'dm_bitset_parse_list' which is also named in version 'DM_1_02_138' in script
/usr/local/bin/ld.gold: error: /usr/local/tmp/ccAQKgvm.ltrans0.ltrans.o: multiple definition of 'dm_bitset_parse_list'
/usr/local/bin/ld.gold: /usr/local/tmp/ccAQKgvm.ltrans0.ltrans.o: previous definition here
    [AR] base/libbase.a
    [AR] device_mapper/libdevice-mapper.a
collect2: error: ld returned 1 exit status
make[1]: *** [../libdm/make.tmpl:422: ioctl/libdevmapper.so.1.02] Error 1
make[1]: Leaving directory '/usr/local/tmp/crew/lvm2.20220302073721.dir/LVM2.2.03.15/libdm'
make: *** [make.tmpl:363: libdm.device-mapper] Error 2
```
I was able to compile this before, but its not working anymore. I dont have another version of lvm2 installed, and I’ve tried on upstream master as well. Exact chromebrew package [here](https://github.com/skycocker/chromebrew/blob/3e2d4850580cbbd5ea61f2224fd2f59717b8225d/packages/lvm2.rb).

**Comment by zkabelac** [comment]
You are most likely linking with system without versioning support ??
Try to use this 'configure'  option  --with-symver=no
(lvm2 is supported with  glibc - other  libc libraries are only supported by  getting extra patches for it...)

**Comment by Zopolis4** [comment]
That does not seem to be an option `configure: WARNING: unrecognized options: --with-symver`

**Comment by Zopolis4** [comment]
Although, `--with-symvers=no` does work.
