### ISSUE TITLE
Avoid blocking on external processes when devices are suspended

### ISSUE THREAD

**Issue by DemiMarie** [lvmteam/lvm2#75]
When devices are suspended, it is not safe to block on other processes, as those processes may themselves be blocked waiting for a device to resume.

**Comment by zkabelac** [comment]
Normally lvm2 is not waiting on other process while being in critical section - however if the 'error' path goes wrong lvm2  may possibly end with leaving  critical section with suspended devices and then possibly even wait on other system tasks.

ATM we are considering such situation as unrecoverable and user has to reboot -  until better fixes/solutions are found.

**Comment by DemiMarie** [comment]
> Normally lvm2 is not waiting on other process while being in critical section - however if the 'error' path goes wrong lvm2 may possibly end with leaving critical section with suspended devices and then possibly even wait on other system tasks.

What can cause this situation to happen?

**Comment by zkabelac** [comment]
> > Normally lvm2 is not waiting on other process while being in critical section - however if the 'error' path goes wrong lvm2 may possibly end with leaving critical section with suspended devices and then possibly even wait on other system tasks.
> 
> What can cause this situation to happen?

Typically kernel bug or target code wrongly handling disk errors - basically very rare condition to ever happen.  Also some seriously critical system resource constrains (i.e. running out of kernel memory)

**Comment by DemiMarie** [comment]
> Also some seriously critical system resource constrains (i.e. running out of kernel memory)

Theoretically lvm2 could retry on this error and hope that it is temporary, but I understand not wanting to.
