### ISSUE TITLE
 undefined reference to `dm_udev_create_cookie'

### ISSUE THREAD

**Issue by SR-dude** [lvmteam/lvm2#8]
When compiling the latest release of ...178, I
get:

dmsetup.o: In function `_udevcreatecookie':
dmsetup.c:(.text+0x574b): undefined reference to `dm_udev_create_cookie'
collect2: error: ld returned 1 exit status

**Comment by zkabelac** [comment]
Dne 21.6.2018 v 19:28 SR-dude napsal(a):
> When compiling the latest release of ...178, I
> get:
> 
> dmsetup.o: In function |_udevcreatecookie': dmsetup.c:(.text+0x574b): 
> undefined reference to|dm_udev_create_cookie'
> collect2: error: ld returned 1 exit status
> 

Hi

Is this compiled with  configure --enable-udev_sync  option  ?

Regards

Zdenek

**Comment by SR-dude** [comment]
Yes, I follow the linux from scratch instructions.

http://linuxfromscratch.org/blfs/view/svn/postlfs/lvm2.html

**Comment by zkabelac** [comment]
Can you attach   configure  && make log ?

**Comment by zkabelac** [comment]
Can we close this issue ?

**Comment by SR-dude** [comment]
Yeah, close it. I still get the unexplained error. But, since I'm a Linux From Scratch user any number of things could go wrong.
