### ISSUE TITLE
vgs with error code -210

### ISSUE THREAD

**Issue by yangni2017** [lvmteam/lvm2#81]
Hello,
CentOS Linux release 8.2.2004 (Core) 
LVM version: 2.03.08(2)-RHEL8 (2020-02-11)

We set up cluster lvm using sanlock as the lock type, and using serval vg in the cluster.
The issue is when the accessing of the storage is still failed, in the case, we can not executed vgs command any more. How to avoid this issue?

the phenomenon is consistent with the  [issue #62](https://github.com/lvmteam/lvm2/issues/62) , but i uses the version of LVM  2.03.15 , the problem is also exist.

Thanks.
The log is as below:
# vgs -vvvvvvvv
18:03:29.584929 vgs[46711] lvmcmdline.c:3140  Version: 2.03.15(2) (2022-02-07)
18:03:29.584974 vgs[46711] lvmcmdline.c:3141  Parsing: vgs -vvvvvvvv
18:03:29.584999 vgs[46711] lvmcmdline.c:2018  Recognised command vgs_general (id 169 / enum 149).
18:03:29.585026 vgs[46711] filters/filter-internal.c:82  Internal filter initialised.
18:03:29.585051 vgs[46711] filters/filter-type.c:61  LVM type filter initialised.
18:03:29.585060 vgs[46711] filters/filter-deviceid.c:66  deviceid filter initialised.
18:03:29.585079 vgs[46711] filters/filter-sysfs.c:106  Sysfs filter initialised.
18:03:29.585100 vgs[46711] filters/filter-usable.c:144  Usable device filter initialised (scan_lvs 0).
18:03:29.585115 vgs[46711] filters/filter-mpath.c:64  mpath filter initialised.
18:03:29.585132 vgs[46711] filters/filter-partitioned.c:76  Partitioned filter initialised.
18:03:29.585143 vgs[46711] filters/filter-signature.c:95  signature filter initialised.
18:03:29.585154 vgs[46711] filters/filter-md.c:157  MD filter initialised.
18:03:29.585164 vgs[46711] filters/filter-composite.c:98  Composite filter initialised.
18:03:29.585190 vgs[46711] filters/filter-persistent.c:197  Persistent filter initialised.
18:03:29.585210 vgs[46711] device_mapper/libdm-config.c:987  devices/hints not found in config: defaulting to "all"
18:03:29.585228 vgs[46711] device_mapper/libdm-config.c:1086  metadata/record_lvs_history not found in config: defaulting to 0
18:03:29.585242 vgs[46711] device_mapper/libdm-config.c:987  devices/search_for_devnames not found in config: defaulting to "auto"
18:03:29.585257 vgs[46711] lvmcmdline.c:3212  DEGRADED MODE. Incomplete RAID LVs will be processed.
18:03:29.585278 vgs[46711] lvmcmdline.c:3218  Processing command: vgs -vvvvvvvv
18:03:29.585292 vgs[46711] lvmcmdline.c:3219  Command pid: 46711
18:03:29.585304 vgs[46711] lvmcmdline.c:3220  System ID: 
18:03:29.585317 vgs[46711] lvmcmdline.c:3223  O_DIRECT will be used
18:03:29.585332 vgs[46711] device_mapper/libdm-config.c:1014  global/locking_type not found in config: defaulting to 1
18:03:29.585356 vgs[46711] locking/locking.c:143  File locking settings: readonly:0 sysinit:0 ignorelockingfailure:0 global/metadata_read_only:0 global/wait_for_locks:1.
18:03:29.585393 vgs[46711] device_mapper/libdm-config.c:987  devices/md_component_checks not found in config: defaulting to "auto"
18:03:29.585409 vgs[46711] lvmcmdline.c:3043  Using md_component_checks auto use_full_md_check 0
18:03:29.585425 vgs[46711] device_mapper/libdm-config.c:987  devices/multipath_wwids_file not found in config: defaulting to "/etc/multipath/wwids"
18:03:29.585465 vgs[46711] device/dev-mpath.c:87  multipath wwids read 0 from /etc/multipath/wwids
18:03:29.585488 vgs[46711] daemon-client.c:31  /run/lvm/lvmlockd.socket: Opening daemon socket to lvmlockd for protocol lvmlockd version 1.
18:03:29.585547 vgs[46711] daemon-client.c:50  Sending daemon lvmlockd: hello
18:03:29.585785 vgs[46711] locking/lvmlockd.c:97  Successfully connected to lvmlockd on fd 3.
18:03:29.585815 vgs[46711] reporter.c:1424  vgs:1424,trx debug,vgs start
18:03:29.585837 vgs[46711] device_mapper/libdm-config.c:987  report/output_format not found in config: defaulting to "basic"
18:03:29.585850 vgs[46711] device_mapper/libdm-config.c:1086  log/report_command_log not found in config: defaulting to 0
18:03:29.585864 vgs[46711] device_mapper/libdm-config.c:1086  report/aligned not found in config: defaulting to 1
18:03:29.585873 vgs[46711] device_mapper/libdm-config.c:1086  report/buffered not found in config: defaulting to 1
18:03:29.585885 vgs[46711] device_mapper/libdm-config.c:1086  report/headings not found in config: defaulting to 1
18:03:29.585894 vgs[46711] device_mapper/libdm-config.c:987  report/separator not found in config: defaulting to " "
18:03:29.585904 vgs[46711] device_mapper/libdm-config.c:1086  report/prefixes not found in config: defaulting to 0
18:03:29.585913 vgs[46711] device_mapper/libdm-config.c:1086  report/quoted not found in config: defaulting to 1
18:03:29.585921 vgs[46711] device_mapper/libdm-config.c:1086  report/columns_as_rows not found in config: defaulting to 0
18:03:29.585931 vgs[46711] device_mapper/libdm-config.c:987  report/vgs_sort not found in config: defaulting to "vg_name"
18:03:29.585940 vgs[46711] device_mapper/libdm-config.c:987  report/vgs_cols_verbose not found in config: defaulting to "vg_name,vg_attr,vg_extent_size,pv_count,lv_count,snap_count,vg_size,vg_free,vg_uuid,vg_profile"
18:03:29.585949 vgs[46711] device_mapper/libdm-config.c:987  report/compact_output_cols not found in config: defaulting to ""
18:03:29.586143 vgs[46711] toollib.c:2221  Processing each VG
18:03:29.586158 vgs[46711] misc/lvm-flock.c:230  Locking /run/lock/lvm/P_global RB
18:03:29.586171 vgs[46711] misc/lvm-flock.c:114  _do_flock /run/lock/lvm/P_global:aux WB
18:03:29.586256 vgs[46711] misc/lvm-flock.c:47  _undo_flock /run/lock/lvm/P_global:aux
18:03:29.586288 vgs[46711] misc/lvm-flock.c:114  _do_flock /run/lock/lvm/P_global RB
18:03:29.586325 vgs[46711] locking/lvmlockd.c:1790  lockd_global:mydebug,lockd_global start...
18:03:29.586337 vgs[46711] locking/lvmlockd.c:1830  lockd global mode sh
18:03:29.588445 vgs[46711] locking/lvmlockd.c:182  lockd_result -210 flags none lm none
18:03:29.588471 vgs[46711] locking/lvmlockd.c:466  lvmlockd lock_gl sh result -210 0
18:03:29.588482 vgs[46711] locking/lvmlockd.c:1889  lockd_global:mydebug,lockd_flags1 = 0
18:03:29.588493 vgs[46711] locking/lvmlockd.c:1947  lockd_global:mydebug,lockd_flags = 0
18:03:29.588500 vgs[46711] locking/lvmlockd.c:1948  Global lock failed: error -210
18:03:29.588511 vgs[46711] misc/lvm-flock.c:84  Unlocking /run/lock/lvm/P_global
18:03:29.588522 vgs[46711] misc/lvm-flock.c:47  _undo_flock /run/lock/lvm/P_global
18:03:29.588557 vgs[46711] toollib.c:2254  <backtrace>
18:03:29.588572 vgs[46711] device_mapper/libdm-config.c:1086  report/compact_output not found in config: defaulting to 0
18:03:29.588590 vgs[46711] daemon-client.c:177  Closing daemon socket (fd 3).
18:03:29.588613 vgs[46711] base/data-struct/hash.c:191  Free hash hint:110 slots:128 nodes:0 (s:0 f:0 c:0 h:0)
18:03:29.588636 vgs[46711] base/data-struct/hash.c:191  Free hash hint:110 slots:128 nodes:0 (s:0 f:0 c:0 h:0)
18:03:29.588649 vgs[46711] cache/lvmcache.c:2589  Destroy lvmcache content
18:03:29.588658 vgs[46711] base/data-struct/hash.c:191  Free hash hint:126 slots:128 nodes:1 (s:1 f:0 c:0 h:0)
18:03:29.588669 vgs[46711] base/data-struct/hash.c:191  Free hash hint:125 slots:128 nodes:0 (s:0 f:0 c:0 h:0)
18:03:29.588681 vgs[46711] base/data-struct/hash.c:191  Free hash hint:127 slots:128 nodes:1 (s:1 f:0 c:0 h:0)
18:03:29.588698 vgs[46711] lvmcmdline.c:3331  Completed: vgs -vvvvvvvv
18:03:29.588959 vgs[46711] cache/lvmcache.c:2589  Destroy lvmcache content
18:03:29.588982 vgs[46711] base/data-struct/hash.c:191  Free hash hint:126 slots:128 nodes:1 (s:1 f:0 c:0 h:0)
18:03:29.588995 vgs[46711] base/data-struct/hash.c:191  Free hash hint:125 slots:128 nodes:0 (s:0 f:0 c:0 h:0)
18:03:29.589003 vgs[46711] base/data-struct/hash.c:191  Free hash hint:127 slots:128 nodes:1 (s:1 f:0 c:0 h:0)
18:03:29.589018 vgs[46711] base/data-struct/hash.c:191  Free hash hint:116 slots:128 nodes:0 (s:0 f:0 c:0 h:0)
18:03:29.589029 vgs[46711] metadata/vg.c:80  Freeing VG #orphans_lvm2 at 0x55d3497a4fa0.
18:03:29.589044 vgs[46711] base/data-struct/hash.c:191  Free hash hint:14 slots:16 nodes:0 (s:0 f:0 c:0 h:0)
18:03:29.589053 vgs[46711] base/data-struct/hash.c:191  Free hash hint:511 slots:512 nodes:0 (s:0 f:0 c:0 h:0)
18:03:29.589074 vgs[46711] base/data-struct/hash.c:191  Free hash hint:1020 slots:1024 nodes:0 (s:0 f:0 c:0 h:0)
18:03:29.589082 vgs[46711] base/data-struct/hash.c:191  Free hash hint:30 slots:32 nodes:0 (s:0 f:0 c:0 h:0)
18:03:29.589089 vgs[46711] base/data-struct/hash.c:191  Free hash hint:29 slots:32 nodes:0 (s:0 f:0 c:0 h:0)
18:03:29.589099 vgs[46711] base/data-struct/hash.c:191  Free hash hint:500 slots:512 nodes:285 (s:390 f:105 c:100 h:0)
18:03:29.589138 vgs[46711] activate/fs.c:492  Syncing device names

![image](https://user-images.githubusercontent.com/24664071/164696421-332aa69e-4312-4930-bfbe-a0e4fbc75074.png)

**Comment by teigland** [comment]
LVM 2.03.15 does not include this upstream lvm commit:
https://sourceware.org/git/?p=lvm2.git;a=commit;h=d14245c72425b99c3bc33a533da46962d010871a
which was the fix for issue https://github.com/lvmteam/lvm2/issues/62

I'm not certain that you have the same problem, but please try that fix to see if it helps.

**Comment by yangni2017** [comment]
it's not work well. I restart the service of lvmlockd,and after 5min the vgs return -210 again. when -210 come, the log print "OP close pid 0 ()"
![image](https://user-images.githubusercontent.com/24664071/164953528-ff0fd548-36a9-4d4b-bbe1-3074b582289d.png)

the other node is ok,and the normal result is as follow:
![image](https://user-images.githubusercontent.com/24664071/164953558-134a8651-022d-4bcf-b292-052bd63df94b.png)

**Comment by zkabelac** [comment]
Assuming bug is now fixed - since there is no reaction for  more then 1/2 year.
