### ISSUE TITLE
mallinfo is not supported on MUSL systems.

### ISSUE THREAD

**Issue by paudley** [lvmteam/lvm2#84]
Hi,
   The mallinfo() function and struct are not available on MUSL based libc systems; by design not omission.   The file "lib/mm/memlock.c" calls it on line 190.  Is there a workaround for this usage?

**Comment by zkabelac** [comment]
Solved upstream with this patch (so it should be compiled only with glibc):

https://listman.redhat.com/archives/lvm-devel/2022-August/024290.html


(And upstream also switched to use  mallinfo2()  since mallinfo() is deprecated by glibc).
