### ISSUE TITLE
Syntax for vgcreate is confusing

### ISSUE THREAD

**Issue by yanadior9029** [lvmteam/lvm2#90]
Please can you review the syntax for vgcreate as it is confusing
current syntax $vgcreate VG_New PV [options]
Please can you elaborate on what is meant by "VG_New" as well as what are the valid Positional Arguments apart from PV.
thank you

**Comment by zkabelac** [comment]
VG_new    is meant to be a new (unused) name for your created VG.
PV is list of devices you want to use for your VG

Accepted options are all IMHO easily visible in both   'man vgcreate'   &  'vgcreate --help' 

https://man7.org/linux/man-pages/man8/vgcreate.8.html

Is there something unclear about the options listing ?

Everything with '-' or '--' is an option (which may eventually consume some args)
Rest is positional arg where 1st. is vgname and remainder is list of PVs....
