### ISSUE TITLE
the snapshot should be recovered quickly

### ISSUE THREAD

**Issue by huang339** [lvmteam/lvm2#95]
the lvconvert that recover snapshot is very slowly, even is intolerable for use

**Comment by zkabelac** [comment]
Could you be please a bit more specific?

Provide some information about your system - ideally  attach output of  'lvmdump' and also some timing and sequence of your commands.

Without further information there is not much other way how to help.

**Comment by zkabelac** [comment]
Closing since no further information was provided in a few months about which type of snapshot or which kind of slowness is actually a problem.
