### ISSUE TITLE
How to delay boot-time activation with multiple LUKS PVs?

### ISSUE THREAD

**Issue by iam-TJ** [lvmteam/lvm2#96]
I have several Debian and Ubuntu systems organised thus:
```
sda > LUKS_A > PV1  \
sdb > LUKS_B > PV2 - VG - LV(s)
sdc > LUKS_C > PV3  /
```
VG contains 50 user-visible LVs although due to RAID-1 there are over 90 with the RAID rimage and rmeta LVs. `rootfs` is one of the RAID-1 LVs.

The LUKS devices are all unlocked by a key-file embedded in the initialramfs (by `cryptsetup-initramfs` scripts) so there is no user-induced delay.

During boot lvm is triggered as soon as the 1st LUKS device is unlocked and its PV detected (by systemd-udevd I presume). As a result there is a long delay as the 90+ LVs are detected but fail activation (with a user-reported warning) because of missing PVs.

Once the missing PVs are opened the LVs are completed with multiple reports of `md/raid1:mdX: active with 2 out of 2 mirrors`

Is there a way to inform LVM either via its configuration, env-vars set by the initramfs-tools hooks/scripts, or udevd rules, to delay activation attempts until all the known PVs are available? I don't want to allow partial-activation.

Here's an extract from the initramfs-tools scripts log that also shows the console log messages:
```
+ /scripts/local-top/lvm2
  WARNING: Couldn't find device with uuid G2PjcM-Txqu-rXuK-wGT6-u2Fh-c2ae-H0s5RD.
  WARNING: Couldn't find device with uuid t66kvr-NTfa-VrG2-fxKg-J079-mnf6-KrWFW8.
  WARNING: VG SUNNY is missing PV G2PjcM-Txqu-rXuK-wGT6-u2Fh-c2ae-H0s5RD (last written to /dev/mapper/LUKS2_OS).
  WARNING: VG SUNNY is missing PV t66kvr-NTfa-VrG2-fxKg-J079-mnf6-KrWFW8 (last written to /dev/mapper/LUKS_WD30EZRZ).
  Refusing activation of partial LV SUNNY/rootfs.  Use '--activationmode partial' to override.
+ '[' -e /conf/param.conf ]
+ /scripts/local-top/cryptroot
WARNING: Couldn't find device with uuid t66kvr-NTfa-VrG2-fxKg-J079-mnf6-KrWFW8.
WARNING: VG SUNNY is missing PV t66kvr-NTfa-VrG2-fxKg-J079-mnf6-KrWFW8 (last written to /dev/mapper/LUKS_WD30EZRZ).
  WARNING: Couldn't find device with uuid t66kvr-NTfa-VrG2-fxKg-J079-mnf6-KrWFW8.
  WARNING: VG SUNNY is missing PV t66kvr-NTfa-VrG2-fxKg-J079-mnf6-KrWFW8 (last written to /dev/mapper/LUKS_WD30EZRZ).
  Refusing activation of partial LV SUNNY/rootfs.  Try '--activationmode degraded'.
  Refusing activation of partial LV SUNNY/var.  Use '--activationmode partial' to override.
  Refusing activation of partial LV SUNNY/NAS.  Try '--activationmode degraded'.
```
This isn't specific to the scripts used by initramfs-tools (they are only used to create the various friendly symbolic links) - it is caused by udevd triggering scans of "add|change" events with device-mapper block devices having a PV signature and LVM attemping 'premature' activation.

I've done quite a bit of experimentation but so far not solved it. I did think that ideally there needs to be something like the existing `devices/md_component_detection = 1` but for dmcrypt devices e.g: `devices/dmcrypt_component_detection = 1`

**Comment by iam-TJ** [comment]
I discovered the reason all LVs were being activated is due to `cryptsetup-initramfs`  code that was forcing a full LV activation after opening each LUKS PV:
```
# /usr/share/initramfs-tools/scripts/local-top/cryptroot::setup_mapping()
...
        elif [ "$fstype" = lvm2 ]; then
            if [ ! -x /sbin/lvm ]; then
                cryptsetup_message "WARNING: $CRYPTTAB_NAME: lvm is not available"
                return 1
            elif vg="$(lvm pvs --noheadings -o vg_name --config 'log{prefix=""}' -- "$dev")"; then
                # activate the VG held by the PV we just unlocked
                lvm lvchange -a y --sysinit -- "$vg"
            fi
        fi
```
Over-riding that with a copy of the same file at `/etc/initramfs-tools/scripts/local-top/cryptroot` with the above section removed appears to have solved the issue. Now, during initialramfs processing the only device-mapper nodes created are the LUKS containers and LVM RAID-1 and user-visible LVs required for the root-fs.

**Comment by ballock** [comment]
I got the same issue. Thanks a lot to @iam-TJ for this analysis and the neat hack. Tested and it works.

**Comment by zkabelac** [comment]
Closing the issue on lvm2 tracer - as it should be resolved in initramfs part ?
